### PR TITLE
use STDOUT for all logging

### PR DESCRIPTION
**Pull request by ceralena**
I noticed this error when testing the built docker image:

	Rails Error: Unable to access log file. Please ensure that /work/log/production.log exists and is writable (i e, make it writable for user and group: chmod 0664 /work/log/production.log). The log level has been raised t o WARN and the output directed to STDERR until the problem is fixed.

Rather than adding a volume to `/work/log` or changing the file
destination, I figure we should just log to stdout anyway if we're
deploying with Docker?

### CODE REVIEW

**Comment by kiesia** [comment]
Maybe we want to do this the rails way? https://github.com/queeraid/exchange/blob/master/config/environments/production.rb#L83

**Comment by ceralena** [comment]
Cool! I've made that change.

**Comment by kiesia** [comment]
@ceralena is this just something that affects prod? Or were you noticing this on dev too?

**Comment by ceralena** [comment]
I only noticed it when doing `docker run` on a built image. Now that I think of it, adding the line to `docker-compose` was pointless.

**Comment by kiesia** [comment]
Close?

**Comment by ceralena** [comment]
I've removed it from `docker-compose`, but kept it in the `Dockerfile`.

**Pull request merged**
